# Generated by Django 3.2.2 on 2021-05-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='<b>User can write their name!</b>', max_length=100)),
                ('email', models.EmailField(help_text='<b>User can write their email!</b>', max_length=100, unique=True)),
                ('hobbies', models.CharField(help_text='<b>User can write their Hobbies!</b>', max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=16)),
            ],
        ),
    ]
